"""Configuration for pytest.

This file includes fixtures and hooks to integrate pytest with other libraries,
such as Loguru.
"""

import pytest


@pytest.fixture
def caplog(caplog):
    """
    Fixture to correctly capture Loguru's output in pytest.

    This overrides the default `caplog` fixture to add a handler that sinks
    logs to the pytest's logging capture manager. This allows assertions
    on log messages generated by Loguru.

    Args:
        caplog: The default pytest caplog fixture.

    Yields:
        The configured caplog fixture.
    """
    from loguru import logger
    handler_id = logger.add(caplog.handler, format="{message}")
    yield caplog
    logger.remove(handler_id)
